#!/usr/bin/python3

import sys

import numpy as np

from earthposition import EarthPosition
from icrsposition import IcrsPosition
from observations import Observations
from orbitalelements import OrbitalElements

if len(sys.argv) != 5:
    print("Simple orbit determination program.")
    print("Usage:")
    print("    python3 main.py [obs_file] i j k")
    print("")
    print("where [obs_file] is an Observer Table ephemeris generated by ")
    print("NASA JPL HORIZONS system containing minimum three observer records ")
    print("with: UT date, RA(ICRF), DEC(ICRF) each,")
    print("and i j and k are three observation numbers from [obs_file]")
    print("which will be used for orbit determination.")

    quit(0)

observations_fname = sys.argv[1]
i = int(sys.argv[2])
j = int(sys.argv[3])
k = int(sys.argv[4])
ijk = (i, j, k)

earthPosition = EarthPosition("earth.csv")
observations = Observations(observations_fname)

icrsposition = IcrsPosition(earthPosition, observations)

phi = icrsposition.phi_angle(ijk)

positions = icrsposition.positions(ijk)

radtodeg = 360/(2*np.pi)

i = 0
for p in positions:
    i += 1
    print(f'Solution: {i}:')
    orbitalElements = OrbitalElements(p)
    elem = orbitalElements.elements()

    inclination = elem.inclination * radtodeg
    if inclination < 0: inclination += 180

    Omega = elem.Omega * radtodeg
    if Omega < 0: Omega += 360

    omega = elem.omega * radtodeg
    if omega < 0: omega += 360

    print(f'i     |                 Inclination: {inclination} deg')
    print(f'Omega | Longitude of ascending node: {Omega} deg')
    print(f'omega |       Argument of periapsis: {omega} deg')
    print(f'a     |             Semi-major axis: {elem.a} au')
    print(f'e     |                Eccentricity: {elem.e}')
    print(f'tp    |           Time of periapsis: {elem.tp} JDTT')

    print()

pass